<?php
$array = array(
    array("ProductId" => "3001",
        "ProductTag" => "Task App",
        "ProductName" => "Vladyno's Task app",
        "ProductPrice" => "$17",
        "ProductDesc" => "It makes your life easier in every step",),
    array("ProductId" => "3002",
        "ProductTag" => "Calculator App",
        "ProductName" => "Vladyno's Calculator app",
        "ProductPrice" => "$15",
        "ProductDesc" => "For all your calculations, comes with a built-in scientific calculator",),
    array("ProductId" => "3003",
        "ProductTag" => "Calendar App",
        "ProductName" => "Vladyno's Calendar app",
        "ProductPrice" => "$25",
        "ProductDesc" => "All your tasks are automagically added to the calendar",),
    array("ProductId" => "3004",
        "ProductTag" => "File Manager",
        "ProductName" => "Vladyno's Explorer",
        "ProductPrice" => "$9.99",
        "ProductDesc" => "A beautiful file manager with plugins to connect to your favorite cloud storage",),
    array("ProductId" => "3005",
        "ProductTag" => "Torchlight",
        "ProductName" => "Vladyno's Lumos",
        "ProductPrice" => "$10",
        "ProductDesc" => "When there is darkness, there is light",),
    array("ProductId" => "3006",
        "ProductTag" => "Gallery",
        "ProductName" => "Vladyno's Memory",
        "ProductPrice" => "$5.99",
        "ProductDesc" => "A personal gallery app that could automatically tag your photos",),
    array("ProductId" => "3007",
        "ProductTag" => "Music Player",
        "ProductName" => "Vladyno's Orchestra",
        "ProductPrice" => "$7.99",
        "ProductDesc" => "The music for your soul, all the music from every source is curated in this app ",),
    array("ProductId" => "3008",
        "ProductTag" => "Reddit Client",
        "ProductName" => "Vladyno's Knowledge",
        "ProductPrice" => "$8.99",
        "ProductDesc" => "One stop for all your curated news from various sources",),
    array("ProductId" => "3009",
        "ProductTag" => "Camera",
        "ProductName" => "Vladyno's Focus",
        "ProductPrice" => "$11.99",
        "ProductDesc" => "A camera app with built in HDR+ and Electronic Image stabilization",),
    array("ProductId" => "3010",
        "ProductTag" => "Message",
        "ProductName" => "Vladyno's Text",
        "ProductPrice" => "$8.99",
        "ProductDesc" => "A beautiful message app with support for RCS",)
);
header('Content-Type: application/json');
echo json_encode($array);

?>